name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash



jobs:
  build_from_makefile:
    name: "Building"
    runs-on: macos-latest
    strategy:
      matrix:
        target_architecture: ["darwin_arm64", "darwin_amd64"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Setup $GOBIN and $PATH
      run: |
        export GOBIN="${HOME}/go/bin"
        mkdir -p ${GOBIN}
        echo "GOBIN=${GOBIN}" >> $GITHUB_ENV
        echo "PATH=${PATH}:${GOBIN}" >> $GITHUB_ENV
    - run: go version
    - run: go env
    - run: echo "gobin ${GOBIN}"
    - run: echo "bash $(which bash)"
    - run: go install fyne.io/fyne/v2/cmd/fyne@v2.3.0
    - run: fyne version
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: make ${{ matrix.target_architecture }}
    - run:  ls -lart ./builds/${{ matrix.target_architecture }}/**/

        

      
