name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash



jobs:
  build_from_makefile:
    env:
      GOBIN: "${{env.GITHUB_ACTION_PATH}}/gobin"
    name: "Building"
    runs-on: ubuntu-latest
    steps:
      - name: Test paths
        run: |
          echo "gobin: ${GOBIN}"
          echo "bash: $(which bash)"

      
