name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash



jobs:
  build_from_makefile:
    name: "Building"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Setup GOPATH and GOBIN
      run: |
        export GOBIN="${HOME}/gobin"
        mkdir -p ${GOBIN}
        echo "GOBIN=${GOBIN}" >> $GITHUB_ENV
    - run: go env
    - run: echo "gobin ${GOBIN}"
    - run: echo "bash $(which bash)"
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install fyne
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest

      
