name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  run_make:
    name: "Run Makefile"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout reporting repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go version
    - name: Run make
      run: |
        make all
        ls -lart ./builds
      
