name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash



jobs:
  build_from_makefile:
    name: "Building"
    runs-on: macos-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go version
    - name: Setup $GOBIN and $PATH
      run: |
        export GOBIN="${HOME}/gobin"
        mkdir -p ${GOBIN}
        echo "GOBIN=${GOBIN}" >> $GITHUB_ENV
        echo "PATH=${PATH}:${GOBIN}" >> $GITHUB_ENV
    - run: go env
    - run: echo "gobin ${GOBIN}"
    - run: echo "bash $(which bash)"
    - run: go install fyne.io/fyne/v2/cmd/fyne@v2.3.0
    - run: go install github.com/fyne-io/fyne-cross@v1.3.0
    - run: fyne version
    - run: fyne-cross version
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: make all
    - run: ls -lart && ls -lart ./fyne-cross/

        

      
