name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash



jobs:
  build_from_makefile:
    name: "Building"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Setup GOPATH and GOBIN
      run: |
        export GOBIN="${GITHUB_WORKSPACE}/gobin"
        echo "GOBIN=${GOBIN}" >> $GITHUB_ENV
    - run: go env
    - run: echo "gopath ${GOPATH}"
    - run: echo "gobin ${GOBIN}"
    - run: echo "bash $(which bash)"

      
