name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  run_make:
    name: "Run Makefile"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout reporting repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Install fyne
      run: |
        export GOBIN="./.gobin/"
        go install fyne.io/fyne/v2/cmd/fyne@latest
    - name: Check versions and vars
      run: |
        go version
        echo "shell $SHELL"
        echo "gobin: ${GOBIN}"
      
