name: "[Build] Create app and release"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  branch_name:
    name: Get branch name
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@main
    secrets: inherit
  semvar_tag:
    needs: [branch_name]
    name: "Get tag for (${{ needs.branch_name.outputs.parsed }})"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-semvar-tag.yml@main
    with:
      branch_name: ${{ needs.branch_name.outputs.parsed }}
    secrets: inherit

  build_from_makefile:
    needs: [branch_name, semvar_tag]
    name: "Building"
    runs-on: macos-latest
    strategy:
      matrix:
        target_architecture: ["darwin_arm64", "darwin_amd64"]
    steps:   
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Setup $GOBIN and $PATH
      run: |
        export GOBIN="${HOME}/go/bin"
        mkdir -p ${GOBIN}
        echo "GOBIN=${GOBIN}" >> $GITHUB_ENV
        echo "PATH=${PATH}:${GOBIN}" >> $GITHUB_ENV
    - run: go install fyne.io/fyne/v2/cmd/fyne@v2.3.0
    - name: Output env & var data
      run: |
        echo "== BRANCH =="
        echo "Raw: ${{ needs.branch_name.outputs.raw }}"
        echo "Parsed: ${{ needs.branch_name.outputs.parsed }}"
        echo "Alphanumeric: ${{ needs.branch_name.outputs.alphanumeric }}"
        echo "== SEMVAR =="
        echo "Tag: ${{ needs.semvar_tag.outputs.tag }}"
        echo "New Tag: ${{ needs.semvar_tag.outputs.new_tag }}"
        echo "== GO =="
        echo "version: $(go version)"        
        echo "gobin: ${GOBIN}"
        echo "fyne: $(fyne version)"
        echo "== PATHING =="
        echo "path: ${PATH}"
        echo "bash $(which bash)"    
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: BUILD via makefile
      run: make ${{ matrix.target_architecture }}
    - run: ls -larth ./builds/${{ matrix.target_architecture }}/**/Contents/MacOS
    - name: Upload application artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OPGAWSKeyRotation_${{ matrix.target_architecture }}.app
        path: ./builds/${{ matrix.target_architecture }}/OPGAWSKeyRotation.app
    - run: echo "done"
  
  create_app_release:
    runs-on: "ubuntu-latest"
    needs: [build_from_makefile, branch_name, semvar_tag]
    name: "Create releases"
    steps:     
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: |
          ls -lart *