name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths: ["**.go"]

defaults:
  run:
    shell: bash

jobs:
  run_make:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout reporting repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run make
      run: |
        make all
        ls -lart ./builds
      
