name: "[Build] Create binary and app"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  build_from_makefile:
    name: "Building"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout reporting repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Install fyne
      run: |
        gbin=$(pwd)/gobin
        mkdir -p ${gbin}
        export GOBIN="${gbin}"
        go install fyne.io/fyne/v2/cmd/fyne@latest
    - name: Check env setup
      run: |
        gbin=$(pwd)/gobin
        export GOBIN="${gbin}"
        export PATH="${PATH}:${GOBIN}"
        go version
        fyne --version
        which bash
        echo "gobin: ${GOBIN}"
        ls -lart
      
